hiddenTabs = []
#Range: 1 ~ 4
itemsPerRow = 4
enchantsBlacklist = ["flimflam", "soulBound","void_floating"]
showDevData = false
dimensionsBlacklist = [-11]
diyData = true
#Range: 1 ~ 4
itemsPerColumn = 4

