#When to show reload button on main menu. By default requires the control key to be pressed.
#Allowed Values: NEVER, RIGHT_CONTROL, RIGHT_ALWAYS, LEFT_CONTROL, LEFT_ALWAYS
"Reload Button" = "RIGHT_CONTROL"
#Reload button offset on x-axis from original position.
#Range: > -2147483648
"Button X-Offset" = 0
#Reload button offset on y-axis from original position.
#Range: > -2147483648
"Button Y-Offset" = 0
#Which side entities can be shown at.
#Allowed Values: LEFT, RIGHT, BOTH
"Entity Side" = "BOTH"
#Size of menu companions.
#Range: > 0
Size = 60
#Offset on x-axis from original position on left side.
#Range: > -2147483648
"Left X-Offset" = 0
#Offset on y-axis from original position on left side.
#Range: > -2147483648
"Left Y-Offset" = 100
#Offset on x-axis from original position on right side.
#Range: > -2147483648
"Right X-Offset" = -25
#Offset on y-axis from original position on right side.
#Range: > -2147483648
"Right Y-Offset" = 80
#Play ambient sounds when clicking on menu mobs.
"Play Sounds" = true
#Volume of ambient sounds.
#Range: 0.0 ~ 1.0
"Sound Volume" = 0.5
#Hurt player when clicked.
"Hurt Player" = true
#Blacklist for excluding entities. Entries will be added automatically when problematic entities are detected.
Blacklist = ["minecraft:ender_dragon", "minecraft:evoker_fangs", "minecraft:falling_block", "minecraft:area_effect_cloud", "minecraft:item", "minecraft:fishing_bobber"]

